services:
  laundromat:
    build: .
    container_name: laundromat
    env_file: .env
    volumes:
      - ./data:/app/data
    environment:
      - DOSSIER_DIR=/app/data/practice
    restart: unless-stopped
    networks:
      - staging

networks:
  staging:
    external: true
